# Generated by Django 3.1.4 on 2022-05-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('prescricao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='patologia',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='horario_previsto',
            field=models.DateTimeField(default='2022-10-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescricao',
            name='responsavel_atual',
            field=models.ForeignKey(default='111.111.111-11', on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_atual', to='pessoa.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='cpf_cadastrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastrante', to='pessoa.usuario'),
        ),
    ]
