# Generated by Django 3.1.4 on 2022-05-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricao', '0002_auto_20220507_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='horario_previsto',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
