# Generated by Django 3.1.4 on 2022-05-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricao', '0003_auto_20220508_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='horario_previsto',
            field=models.DateTimeField(),
        ),
    ]
