# Generated by Django 3.1.4 on 2022-05-08 03:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prescricao', '0003_auto_20220508_0003'),
        ('ocorrencia', '0003_auto_20220508_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='id_ocorrencia',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='prescricao_associada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescricao.prescricao'),
        ),
    ]
