# Generated by Django 3.1.4 on 2022-05-05 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescricao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_correspondente', models.CharField(max_length=1)),
                ('horario', models.DateTimeField(auto_now=True)),
                ('prescrisao_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescricao.prescricao')),
            ],
        ),
    ]
