# Generated by Django 3.1.4 on 2022-05-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('prescricao', '0002_auto_20220507_1618'),
        ('horario', '0002_auto_20220505_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='cpf_responsavel',
            field=models.ForeignKey(default='111.111.111-11', on_delete=django.db.models.deletion.CASCADE, to='pessoa.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='prescricao_associada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prescricao.prescricao'),
        ),
    ]
