# Generated by Django 3.1.4 on 2022-04-28 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescricao', '__first__'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id_ocorrencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=255)),
                ('cpf_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.paciente')),
                ('prescicao_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescricao.prescricao')),
                ('usuario_cadastrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.usuario')),
            ],
        ),
    ]
